# config/ablation_base.yaml
# A configuration for a FAST and INFORMED ablation study.
# - Uses the optimal architecture found by Optuna.
# - Uses a smaller dataset and fewer epochs for speed.

training:
  # --- Optimal parameters from the interrupted 'production' run ---
  batch_size: 128                              # <-- From Optuna
  learning_rate: 0.0029954385433438864         # <-- From Optuna
  weight_decay: 0.000011549001876236783       # <-- From Optuna
  hidden_sizes: [512, 256, 64]                 # <-- From Optuna
  dropout_rate: 0.10781884498874056            # <-- From Optuna
  
  n_ensembles: 1                               # <-- Reduced for speed
  steps_per_epoch_stage1: 15                   # <-- Reduced for speed
  steps_per_epoch_stage2: 8                    # <-- Reduced for speed
  n_epochs_stage1: 30                          # <-- Reduced for speed
  n_epochs_stage2: 15                          # <-- Reduced for speed
  validation_steps_per_epoch: 10               # <-- MODIFIED: Added for iterable validation

  # --- These values will be OVERWRITTEN by the run_ablation.sh script ---
  loss_pinn_weight_stage1: 1.0
  loss_pinn_weight_stage2: 0.1
  
  # --- Other necessary model parameters ---
  norm_type: "batch"
  learning_rate_stage2: 0.0002
  use_transformer_temporal_model: true
  m0_input_feature_model: false
  use_focused_transformer_model: true
  transformer_d_model_focused: 32
  transformer_nhead_model: 4
  transformer_nlayers_model: 2
  log_var_cbf_min: -6.0
  log_var_cbf_max: 7.0
  log_var_att_min: -2.0
  log_var_att_max: 14.0
  loss_weight_cbf: 1.0
  loss_weight_att: 2.0
  loss_log_var_reg_lambda: 0.0

data:
  pld_values: [500, 1000, 1500, 2000, 2500, 3000]
  att_ranges_config:
    - [500, 1500, "Short ATT"]
    - [1500, 2500, "Medium ATT"]
    - [2500, 4000, "Long ATT"]
  include_m0_in_training_data: false

evaluation:
  n_test_subjects_per_att_range: 50 # Reduced for speed
  n_clinical_scenario_subjects: 20  # Reduced for speed

simulation:
  T1_artery: 1850.0
  T2_factor: 1.0
  alpha_BS1: 1.0
  alpha_PCASL: 0.85
  alpha_VSASL: 0.56
  T_tau: 1800.0
  reference_CBF: 60.0

optuna:
  optuna_n_trials: 0
  optuna_study_name: "ablation_run"

logging:
  level: "INFO"

wandb: 
  wandb_project: "asl-multiverse-ablation"
  wandb_entity: null