# config/debug.yaml
#
# A special configuration to visually test the 3-stage curriculum logic.

training:
  batch_size: 4
  n_ensembles: 1
  dropout_rate: 0.1
  norm_type: "batch"
  validation_steps_per_epoch: 1
  
  # --- Stage-specific Learning Rates (to test the logic) ---
  learning_rate_cbf: 0.0025
  learning_rate_att: 0.0005
  learning_rate_stage2_cbf: 0.0001
  learning_rate_stage2_att: 0.00005

  # --- V3 3-Stage Training Schedule (MINIATURE VERSION) ---
  # We use small, distinct numbers to prove each stage is running.
  n_epochs_stage0_pretrain: 2      # STAGE 0 will run for 2 epochs
  steps_per_epoch_stage0_pretrain: 1
  
  n_epochs_stage1: 3               # STAGE 1 will run for 3 epochs
  steps_per_epoch_stage1: 1
  
  n_epochs_stage2: 1               # STAGE 2 will run for 1 epoch
  steps_per_epoch_stage2: 1
  
  # --- Other parameters needed to run ---
  hidden_sizes: [8, 4]
  weight_decay: 0.00001
  loss_pinn_weight_stage1: 1.0
  loss_pinn_weight_stage2: 0.1
  pre_estimator_loss_weight_stage1: 1.0
  pre_estimator_loss_weight_stage2: 0.0
  use_transformer_temporal_model: true
  m0_input_feature_model: false
  use_focused_transformer_model: true
  transformer_d_model_focused: 8
  transformer_nhead_model: 2
  transformer_nlayers_model: 1
  loss_weight_cbf: 1.0
  loss_weight_att: 2.0

data:
  use_offline_dataset: false # Use on-the-fly generation for this test
  pld_values: [500, 1000, 1500, 2000, 2500, 3000]
  num_samples: 100

simulation:
  T1_artery: 1850.0
  T_tau: 1800.0

wandb: 
  wandb_project: "asl-curriculum-test"