# config/debug_validation.yaml
#
# A configuration for a FAST (~30 min) run to validate data generation fixes.
# It uses a small but effective model and a compressed 3-stage curriculum.

training:
  # --- Use a larger batch size for speed and stability ---
  batch_size: 2048
  n_ensembles: 1 # Only need one model for this test
  
  # --- Use production-level architecture for a realistic test ---
  hidden_sizes: [512, 256, 128]
  dropout_rate: 0.1
  weight_decay: 0.00001
  norm_type: "batch"
  
  # --- Use production-level LRs to test stability ---
  learning_rate_cbf: 0.0025
  learning_rate_att: 0.0005
  learning_rate_stage2_cbf: 0.0001
  learning_rate_stage2_att: 0.00005

  # --- Key parameters for validation speed ---
  validation_steps_per_epoch: 25 # Get frequent, meaningful validation feedback

  # ==========================================================
  # --- ACCELERATED 3-STAGE CURRICULUM ---
  # ==========================================================

  # Stage 0: Physics Stabilization (5-10 mins)
  # Goal: See if the PINN loss helps the model find a reasonable starting point.
  n_epochs_stage0_pretrain: 10
  steps_per_epoch_stage0_pretrain: 50
  loss_pinn_weight_stage0: 2.0
  pre_estimator_loss_weight_stage0: 1.0

  # Stage 1: Data Generalization (10-15 mins)
  # Goal: See if the model learns from the broader data distribution.
  n_epochs_stage1: 10
  steps_per_epoch_stage1: 50
  loss_pinn_weight_stage1: 0.1
  pre_estimator_loss_weight_stage1: 0.0

  # Stage 2: Hard-Case Fine-Tuning (5-10 mins)
  # Goal: See if the model can adapt to a different data sampling strategy.
  n_epochs_stage2: 5
  steps_per_epoch_stage2: 50
  loss_pinn_weight_stage2: 0.1
  pre_estimator_loss_weight_stage2: 0.0
  loss_weight_att_stage2: 8.0 # Override default ATT weight

  # --- Default Loss Weights (used unless overridden by a stage) ---
  loss_weight_cbf: 1.0
  loss_weight_att: 1.0
  
  # --- Other Model/Loss Parameters (same as production) ---
  use_transformer_temporal_model: true
  use_focused_transformer_model: true
  transformer_d_model_focused: 32
  transformer_nhead_model: 4
  transformer_nlayers_model: 2

data:
  # CRITICAL: We need the offline dataset for the Stage 2 weighted sampler to work.
  # The run will fail if this is set to false.
  use_offline_dataset: true
  # You must have generated the offline dataset with the FIXED simulation code first.
  # Point this to your newly generated clean dataset.
  offline_dataset_path: "asl_offline_dataset_10M_FIXED" # Or whatever you named it
  
  # These are needed for the model and data generation
  pld_values: [500, 1000, 1500, 2000, 2500, 3000]
  num_samples: 10000 # For norm_stats calculation if needed

simulation:
  T1_artery: 1850.0
  T_tau: 1800.0

wandb: 
  wandb_project: "asl-fix-validation"
  wandb_entity: null # Your W&B entity