# config/default.yaml

training:
  batch_size: 256
  learning_rate: 0.001
  weight_decay: 0.00001
  hidden_sizes: [256, 128, 64] 
  n_ensembles: 5
  dropout_rate: 0.1
  norm_type: "batch"
  
  steps_per_epoch_stage1: 20
  steps_per_epoch_stage2: 40
  n_epochs_stage1: 140
  n_epochs_stage2: 60
  validation_steps_per_epoch: 50 # <-- MODIFIED: Added for iterable validation
  
  loss_pinn_weight_stage1: 1.0
  loss_pinn_weight_stage2: 0.1
  learning_rate_stage2: 0.0002
  
  use_transformer_temporal_model: true
  m0_input_feature_model: false 
  use_focused_transformer_model: true 
  transformer_d_model_focused: 32     
  transformer_nhead_model: 4
  transformer_nlayers_model: 2
  log_var_cbf_min: -6.0
  log_var_cbf_max: 7.0
  log_var_att_min: -2.0
  log_var_att_max: 14.0
  loss_weight_cbf: 1.0
  loss_weight_att: 2.0
  loss_log_var_reg_lambda: 0.0

data:
  pld_values: [500, 1000, 1500, 2000, 2500, 3000]
  att_ranges_config:
    - [500, 1500, "Short ATT"]
    - [1500, 2500, "Medium ATT"]
    - [2500, 4000, "Long ATT"]
  include_m0_in_training_data: false
  
evaluation:
  n_test_subjects_per_att_range: 200
  n_clinical_scenario_subjects: 100

simulation:
  T1_artery: 1850.0
  T2_factor: 1.0
  alpha_BS1: 1.0
  alpha_PCASL: 0.85
  alpha_VSASL: 0.56
  T_tau: 1800.0
  reference_CBF: 60.0

optuna:
  optuna_n_trials: 20
  optuna_timeout_hours: 0.5
  optuna_n_subjects: 500
  optuna_n_epochs: 20
  optuna_study_name: "asl_multiverse_hpo"

logging:
  level: "INFO"

wandb: 
  wandb_project: "asl-multiverse-project"
  wandb_entity: null