training:
  batch_size: 256
  learning_rate: 0.001
  hidden_sizes: [256, 128, 64]
  n_epochs: 200
  n_ensembles: 5
  dropout_rate: 0.1
  norm_type: "batch"

data:
  n_samples: 20000
  val_split: 0.2
  pld_range: [500, 3000, 500]  # start, end, step
  att_ranges:
    - [500, 1500, "Short ATT"]
    - [1500, 2500, "Medium ATT"]
    - [2500, 4000, "Long ATT"]

model:
  input_size: 12  # 6 PLDs * 2 (PCASL + VSASL)
  use_curriculum: true
  early_stopping_patience: 20

simulation:
  T1_artery: 1850
  T2_factor: 1
  alpha_BS1: 1
  alpha_PCASL: 0.85
  alpha_VSASL: 0.56
  T_tau: 1800
  CBF: 60

logging:
  level: "INFO"
  log_dir: "logs"
  save_frequency: 10  # epochs

paths:
  model_dir: "models"
  results_dir: "results"
  data_dir: "data"