# FILE: config/production_disentangled.yaml
# config/production_disentangled.yaml
#
# Definitive configuration for a full-scale production training run of the
# NEW DisentangledASLNet v3 architecture with the unified training strategy.

training:
  # --- Key to activate the v2 model ---
  model_class_name: "DisentangledASLNet"

  # --- Architecture & Regularization (Based on prior HPO) ---
  hidden_sizes: [512, 256, 128]
  dropout_rate: 0.0878
  weight_decay: 0.0000138

  # --- Learning Rate & Production Scale Parameters ---
  learning_rate: 0.0005 
  batch_size: 8192
  n_ensembles: 5
  validation_steps_per_epoch: 50
  norm_type: "batch"
  n_epochs: 100 # A single, unified training run

  # --- Principled Unified Loss Weights & v3 Additions ---
  loss_pinn_weight: 0.5
  residual_pinn_weight: 0.01 # NEW: Weight for the GKM physics residual loss
  loss_weight_cbf: 1.0       # MODIFIED: Trust Uncertainty Weighting
  loss_weight_att: 1.0       # MODIFIED: Trust Uncertainty Weighting
  loss_log_var_reg_lambda: 0.001
  ohem_fraction: 0.5         # NEW: Fraction of hardest examples to use for training (1.0 disables OHEM)


  # --- Core Model/Loss Parameters ---
  log_var_cbf_min: -6.0
  log_var_cbf_max: 7.0
  log_var_att_min: -2.0
  log_var_att_max: 14.0
  use_transformer_temporal_model: true # Placeholder
  use_focused_transformer_model: true # Placeholder
  transformer_d_model_focused: 32
  transformer_nhead_model: 4
  transformer_nlayers_model: 2

data:
  # --- CRITICAL: Requires a large, pre-generated offline dataset with the v3 UNBIASED data strategy ---
  use_offline_dataset: true
  offline_dataset_path: "asl_offline_dataset_10M_v3" # MUST point to the new UNBIASED dataset
  pld_values: [500, 1000, 1500, 2000, 2500, 3000]
  num_samples: 1000000 # Number of samples for norm_stats calculation if needed

simulation:
  T1_artery: 1850.0
  T_tau: 1800.0
  T2_factor: 1.0
  alpha_BS1: 1.0
  alpha_PCASL: 0.85
  alpha_VSASL: 0.56
  T1_tissue: 1331.0 # NEW: T1 of gray matter tissue for GKM residual calculation

wandb:
  wandb_project: "asl-multiverse-disentangled-prod-v3" # New project for this run
  wandb_entity: "adikondepudi" # Your W&B entity, if you have one