# config/production_final.yaml
#
# The definitive configuration for the final, efficient production run.
# Implements a 3-stage curriculum learning strategy with a UNIFIED regression head.

training:
  # --- HPO values for architecture and regularization ---
  hidden_sizes: [512, 256, 128]
  dropout_rate: 0.0878
  weight_decay: 0.0000138

  # --- Differential Learning Rates for Stability ---
  # REVISED: With the unified head, only the 'att' LR is used for all parameters.
  # The 'cbf' LR is now obsolete and has been removed for clarity.
  learning_rate_att: 0.0005          # LR for foundational stages (0 & 1)
  learning_rate_stage2_att: 0.00005  # Reduced LR for fine-tuning (Stage 2)

  # --- Production run parameters ---
  batch_size: 8192
  n_ensembles: 5
  validation_steps_per_epoch: 50
  norm_type: "batch"

  # ==========================================================
  # --- NEW 3-STAGE CURRICULUM DEFINITION ---
  # ==========================================================

  # Stage 0: Physics-Driven Stabilization (Unbiased Sampler)
  n_epochs_stage0_pretrain: 25
  loss_pinn_weight_stage0: 2.0
  pre_estimator_loss_weight_stage0: 1.0

  # Stage 1: Data-Driven Generalization (Unbiased Sampler)
  n_epochs_stage1: 75
  loss_pinn_weight_stage1: 0.1
  pre_estimator_loss_weight_stage1: 0.0

  # Stage 2: Hard-Case Fine-Tuning (Weighted Sampler)
  n_epochs_stage2: 30
  loss_pinn_weight_stage2: 0.1
  pre_estimator_loss_weight_stage2: 0.0
  loss_weight_att_stage2: 8.0 # Override default ATT weight for this stage
  # ==========================================================

  # --- Default Loss Weights (used unless overridden by a stage) ---
  loss_weight_cbf: 1.0
  loss_weight_att: 1.0

  # --- Other Model/Loss Parameters ---
  log_var_cbf_min: -6.0
  log_var_cbf_max: 7.0
  log_var_att_min: -2.0
  log_var_att_max: 14.0
  loss_log_var_reg_lambda: 0.001
  use_transformer_temporal_model: true
  use_focused_transformer_model: true
  transformer_d_model_focused: 32
  transformer_nhead_model: 4
  transformer_nlayers_model: 2

data:
  # This curriculum requires the offline dataset for the weighted sampler
  use_offline_dataset: true
  offline_dataset_path: "asl_offline_dataset_10M"
  pld_values: [500, 1000, 1500, 2000, 2500, 3000]
  num_samples: 1000000 # for norm_stats calculation

simulation:
  T1_artery: 1850.0
  T_tau: 1800.0
  # other sim params are not strictly needed here but are good for record-keeping
  T2_factor: 1.0
  alpha_BS1: 1.0
  alpha_PCASL: 0.85
  alpha_VSASL: 0.56

wandb:
  wandb_project: "asl-multiverse-production-final"
  wandb_entity: null