# config/short_debug.yaml
# A minimal configuration to test the full 3-stage training pipeline in <5 minutes.

training:
  # --- HPO values for architecture and regularization ---
  hidden_sizes: [512, 256, 128]
  dropout_rate: 0.0878
  weight_decay: 0.0000138

  # --- Differential Learning Rates for Stability ---
  learning_rate_att: 0.0005
  learning_rate_stage2_att: 0.00005

  # --- Run parameters ---
  batch_size: 8192 # Keep batch size high to test memory
  n_ensembles: 1 # Only one model needed for a dry run
  validation_steps_per_epoch: 5 # Few steps for speed
  norm_type: "batch"

  # --- ACCELERATED 3-STAGE CURRICULUM ---
  n_epochs_stage0_pretrain: 2 # <-- REDUCED
  loss_pinn_weight_stage0: 2.0
  pre_estimator_loss_weight_stage0: 1.0

  n_epochs_stage1: 2 # <-- REDUCED
  loss_pinn_weight_stage1: 0.1
  pre_estimator_loss_weight_stage1: 0.0

  n_epochs_stage2: 2 # <-- REDUCED
  loss_pinn_weight_stage2: 0.1
  pre_estimator_loss_weight_stage2: 0.0
  loss_weight_att_stage2: 8.0

  # --- Other Model/Loss Parameters ---
  loss_weight_cbf: 1.0
  loss_weight_att: 1.0
  log_var_cbf_min: -6.0
  log_var_cbf_max: 7.0
  log_var_att_min: -2.0
  log_var_att_max: 14.0
  loss_log_var_reg_lambda: 0.001
  use_transformer_temporal_model: true
  use_focused_transformer_model: true
  transformer_d_model_focused: 32
  transformer_nhead_model: 4
  transformer_nlayers_model: 2

data:
  use_offline_dataset: true
  offline_dataset_path: "asl_offline_dataset_10M" # MUST MATCH YOUR REAL PATH
  pld_values: [500, 1000, 1500, 2000, 2500, 3000]
  num_samples: 10000 # Use a small number for norm stats if they need to be recalculated

simulation:
  T1_artery: 1850.0
  T_tau: 1800.0
  T2_factor: 1.0
  alpha_BS1: 1.0
  alpha_PCASL: 0.85
  alpha_VSASL: 0.56

wandb:
  wandb_project: "asl-multiverse-dry-run" # Log to a separate project
  wandb_entity: null