# config/final_v11_training.yaml

training:
  # --- Architecture & Regularization (These are solid) ---
  hidden_sizes: [512, 256, 128]
  dropout_rate: 0.0878
  weight_decay: 0.0000138

  # --- A single, stable learning rate ---
  learning_rate_att: 0.0005

  # --- Production run parameters ---
  batch_size: 8192
  n_ensembles: 5
  validation_steps_per_epoch: 50
  norm_type: "batch"

  # ==========================================================
  # --- 3-STAGE CURRICULUM ---
  # ==========================================================

  # Stage 0: Gentle Physics Guidance (25 epochs)
  n_epochs_stage0_pretrain: 25
  loss_pinn_weight_stage0: 0.1
  pre_estimator_loss_weight_stage0: 0.1

  # Stage 1: Data-Driven Generalization (75 epochs)
  n_epochs_stage1: 75
  loss_pinn_weight_stage1: 0.0
  pre_estimator_loss_weight_stage1: 0.0

  # Stage 2: Hard-Case Fine-Tuning (30 epochs)
  n_epochs_stage2: 30
  loss_pinn_weight_stage2: 0.0
  pre_estimator_loss_weight_stage2: 0.0

  loss_weight_cbf: 1.0
  loss_weight_att: 2.5
  loss_weight_att_stage2: 2.5 
  # ==========================================================

  # --- Core Model/Loss Parameters ---
  log_var_cbf_min: -6.0
  log_var_cbf_max: 7.0
  log_var_att_min: -2.0
  log_var_att_max: 14.0
  loss_log_var_reg_lambda: 0.001
  use_transformer_temporal_model: true
  use_focused_transformer_model: true
  transformer_d_model_focused: 32
  transformer_nhead_model: 4
  transformer_nlayers_model: 2

data:
  use_offline_dataset: true
  offline_dataset_path: "asl_offline_dataset_10M" # Use the ultimate dataset
  pld_values: [500, 1000, 1500, 2000, 2500, 3000]
  num_samples: 1000000

simulation:
  T1_artery: 1850.0
  T_tau: 1800.0
  T2_factor: 1.0
  alpha_BS1: 1.0
  alpha_PCASL: 0.85
  alpha_VSASL: 0.56

wandb:
  wandb_project: "asl-multiverse-production-final"
  wandb_entity: null