# FILE: config/v4_stage2.yaml
# Configuration for the v4 fine-tuning stage (Stage 2).
# Loads a pre-trained encoder, freezes it, and fine-tunes the heads.

training:
  # --- Key to activate the v3 model ---
  model_class_name: "DisentangledASLNet"

  # --- Key Fine-Tuning Parameters ---
  # NOTE: This path is a placeholder; it will be overwritten by the run script.
  pretrained_encoder_path: "path/to/stage1/encoder_pretrained.pt" 
  fine_tuning_freeze_epochs: 15

  # --- Architecture & Regularization (must match Stage 1) ---
  hidden_sizes: [512, 256, 128]
  dropout_rate: 0.0878
  weight_decay: 0.0000138

  # --- Learning Rate & Production Scale Parameters ---
  learning_rate: 0.00005     # CRITICAL: Lower LR for fine-tuning
  batch_size: 8192
  n_ensembles: 5
  validation_steps_per_epoch: 50
  norm_type: "batch"
  n_epochs: 40               # Shorter run for fine-tuning

  # --- Loss Weights for Fine-tuning ---
  loss_pinn_weight: 0.1      # Reduced physics guidance
  residual_pinn_weight: 0.0
  loss_weight_cbf: 1.0
  loss_weight_att: 1.0
  loss_log_var_reg_lambda: 0.001
  ohem_fraction: 0.75        # CRITICAL: Focus on 75% hardest examples

  # --- Core Model/Loss Parameters (must match Stage 1) ---
  log_var_cbf_min: -6.0
  log_var_cbf_max: 7.0
  log_var_att_min: -2.0
  log_var_att_max: 14.0
  transformer_d_model_focused: 32
  transformer_nhead_model: 4
  transformer_nlayers_model: 2

data:
  use_offline_dataset: true
  offline_dataset_path: "asl_offline_dataset_10M_v3"
  pld_values: [500, 1000, 1500, 2000, 2500, 3000]
  num_samples: 1000000 

simulation:
  T1_artery: 1850.0
  T_tau: 1800.0
  T2_factor: 1.0
  alpha_BS1: 1.0
  alpha_PCASL: 0.85
  alpha_VSASL: 0.56
  T1_tissue: 1331.0 

wandb:
  wandb_project: "asl-multiverse-prod-v4-stage2"
  wandb_entity: "adikondepudi"