# FILE: config/v4_stage1.yaml
# Configuration for the v4 pre-training stage (Stage 1).
# Trains the full model from scratch on the complete dataset.

training:
  # --- Key to activate the v3 model ---
  model_class_name: "DisentangledASLNet"

  # --- Architecture & Regularization (Based on prior HPO) ---
  hidden_sizes: [512, 256, 128]
  dropout_rate: 0.0878
  weight_decay: 0.0000138

  # --- Learning Rate & Production Scale Parameters ---
  learning_rate: 0.001       # Standard LR for training from scratch
  batch_size: 8192
  n_ensembles: 5
  validation_steps_per_epoch: 50
  norm_type: "batch"
  n_epochs: 80               # Long run for full convergence

  # --- Principled Unified Loss Weights for Pre-training ---
  loss_pinn_weight: 0.5
  residual_pinn_weight: 0.01 
  loss_weight_cbf: 1.0
  loss_weight_att: 1.0
  loss_log_var_reg_lambda: 0.001
  ohem_fraction: 1.0         # CRITICAL: Use the full dataset (OHEM is disabled)

  # --- Core Model/Loss Parameters ---
  log_var_cbf_min: -6.0
  log_var_cbf_max: 7.0
  log_var_att_min: -2.0
  log_var_att_max: 14.0
  transformer_d_model_focused: 32
  transformer_nhead_model: 4
  transformer_nlayers_model: 2

data:
  use_offline_dataset: true
  offline_dataset_path: "asl_offline_dataset_10M_v3"
  pld_values: [500, 1000, 1500, 2000, 2500, 3000]
  num_samples: 1000000 

simulation:
  T1_artery: 1850.0
  T_tau: 1800.0
  T2_factor: 1.0
  alpha_BS1: 1.0
  alpha_PCASL: 0.85
  alpha_VSASL: 0.56
  T1_tissue: 1331.0 

wandb:
  wandb_project: "asl-multiverse-prod-v4-stage1"
  wandb_entity: "adikondepudi"